# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVWqXJSFX8IsUD8ajnreCHAl7fTI4bhI
"""

!pip install -q streamlit transformers torch
import streamlit as st
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 1. Page Title & Description
st.title("🎭 Text Emotion Detector")
st.write("Enter any English text to detect emotions (Joy, Sadness, Anger, Fear, Surprise, Neutral, Disgust).")

# 2. Load Pretrained Model & Tokenizer
@st.cache_resource
def load_model():
    model_name = "j-hartmann/emotion-english-distilroberta-base"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    return tokenizer, model

tokenizer, model = load_model()

# 3. Dictionary to map emotion labels to emojis
EMOJI_MAP = {
    "joy": "😄 Joy",
    "sadness": "😢 Sadness",
    "anger": "😡 Anger",
    "fear": "😨 Fear",
    "surprise": "😲 Surprise",
    "disgust": "🤢 Disgust",
    "neutral": "😐 Neutral"
}

# 4. User Input Textbox
text_input = st.text_area("Type your text here...", "I am so happy and excited about this project!")

# 5. Prediction Logic on Button Click
if st.button("Analyze Emotion"):
    if text_input.strip() != "":
        inputs = tokenizer(text_input, return_tensors="pt", truncation=True)
        with torch.no_grad():
            outputs = model(**inputs)

        probs = torch.softmax(outputs.logits, dim=1)[0]
        labels = model.config.id2label

        # Sort and map results
        results = {EMOJI_MAP.get(labels[i], labels[i]): float(probs[i]) for i in range(len(labels))}
        sorted_results = sorted(results.items(), key=lambda x: x[1], reverse=True)

        st.subheader("Results:")
        for label, prob in sorted_results[:4]:
            st.write(f"**{label}**: {prob*100:.1f}%")
            st.progress(prob)