# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KU9Yh9bCBPInZjqvPiyQvwWAdIKx_GsK
"""

!pip -q install transformers torch gradio

import torch
import gradio as gr
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Choose pretrained model for Emotion Detection
MODEL_NAME = "j-hartmann/emotion-english-distilroberta-base"

print("Loading model...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)

# Dictionary to map emotion labels to emojis
EMOJI_MAP = {
    "joy": "😄 Joy",
    "sadness": "😢 Sadness",
    "anger": "😡 Anger",
    "fear": "😨 Fear",
    "surprise": "😲 Surprise",
    "disgust": "🤢 Disgust",
    "neutral": "😐 Neutral"
}

# Define prediction function
def predict_emotion(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)

    # Convert logits to probabilities
    probs = torch.softmax(outputs.logits, dim=1)[0]

    # Get labels from model config
    labels = model.config.id2label

    # Return dictionary using EMOJI_MAP
    results = {EMOJI_MAP.get(labels[i], labels[i]): float(probs[i]) for i in range(len(labels))}
    return results

# Create Gradio Interface
demo = gr.Interface(
    fn=predict_emotion,
    inputs=gr.Textbox(lines=3, placeholder="Type your text here..."),
    outputs=gr.Label(num_top_classes=4),
    title="🎭 Text Emotion Detector",
    description="Enter any English text to detect emotions (Joy, Sadness, Anger, Fear, Surprise, Neutral, Disgust).",
    examples=[
        ["I am so happy and excited about this project!"],
        ["I feel so lonely and sad today."],
        ["Get out of here right now!"],
        ["Oh my god, I cannot believe I won the prize!"],
        ["I heard a scary noise outside in the dark."],
    ]
)

demo.launch()